### ISSUE TITLE
Tornado Speed   |   Meteor speed/despawn rate

### ISSUE THREAD

**Issue by AkumaNoTenshi** [XuuXiao/CodeRebirthReports#1]
It would be nice if we could edit the speed of Tornadoes and how long it takes for meteors to crash and despawn.

**Comment by XuuXiao** [comment]
I can probably make this really quick, it'll probably be with the next version

**Comment by AkumaNoTenshi** [comment]
Thank you for your response, I look forward to seeing it.

**Comment by XuuXiao** [comment]
added to dev release
